# Generated by Django 2.2.4 on 2019-08-31 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20190831_1803'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='resturant',
        ),
        migrations.AddField(
            model_name='category',
            name='resturant',
            field=models.ManyToManyField(blank=True, null=True, to='pos.Restaurant'),
        ),
    ]
